config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :task_types
  resources :tasks
  devise_for :users

  get '/landing', to: 'application#landing'
  get '/admin', to: 'application#admin'

  root to: "application#landing"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/task_type.rb
class TaskType < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :authenticate_admin!, only: :admin

    def admin; end

    def landing; end

    private

    def authenticate_admin!
        redirect_to landing_path unless current_user.admin?
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:[name[)
    end
end

app/controllers/task_types_controller.rb
class TaskTypesController < ApplicationController
  before_action :set_task_type, only: [:show, :edit, :update, :destroy]

  # GET /task_types
  # GET /task_types.json
  def index
    @task_types = TaskType.all
  end

  # GET /task_types/1
  # GET /task_types/1.json
  def show
  end

  # GET /task_types/new
  def new
    @task_type = TaskType.new
  end

  # GET /task_types/1/edit
  def edit
  end

  # POST /task_types
  # POST /task_types.json
  def create
    @task_type = TaskType.new(task_type_params)

    respond_to do |format|
      if @task_type.save
        format.html { redirect_to @task_type, notice: 'Task type was successfully created.' }
        format.json { render :show, status: :created, location: @task_type }
      else
        format.html { render :new }
        format.json { render json: @task_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_types/1
  # PATCH/PUT /task_types/1.json
  def update
    respond_to do |format|
      if @task_type.update(task_type_params)
        format.html { redirect_to @task_type, notice: 'Task type was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_type }
      else
        format.html { render :edit }
        format.json { render json: @task_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_types/1
  # DELETE /task_types/1.json
  def destroy
    @task_type.destroy
    respond_to do |format|
      format.html { redirect_to task_types_url, notice: 'Task type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_type
      @task_type = TaskType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_type_params
      params.require(:task_type).permit(:[name[)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:customer_id, :type_id, :user_id, :title, :description, :start_time, :end_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/task_types_helper.rb
module TaskTypesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/application/admin.html.erb
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="css/style.css">
    <script src="js/timer.js"></script>
    <title>Admin</title>
</head>
<body>
<div class="wrapper">

    <div class="nav" id="nav">
        <ul>
<!--             <li><a id="starttimer" onclick="timer()" >Start</a></li> -->
            <li><a href="#">second</a></li>
            <li><a href="#">three</a></li>
            <li><a href="#">four</a></li>
            <li><a href="#">five</a></li>
        </ul>
    </div>

    <div class="header">
        <div class="logo"><img src="assets/d2dzjyo4yc2sta.cloudfront.net.jpg" alt="logo"></div>
        <p class="name-email">Фамилия и Email</p>
        <p id="timer"></p>

        <div id="burger-menu">
            <div class="menu">
                <div class="first-line"></div>
                <div class="second-line"></div>
                <div class="three-line"></div>
            </div>
        </div>
    </div>

    <div class="content-md-lg">
        <table cellpadding="10" border="1" width="100%">
            <tr>
                <th>Сотрудники</th>
                <th><a href="#">E-mail</a></th>
                <th>Задачи</th>
                <th>Время</th>
                <th>Статус</th>
                <th>Даные работника</th>
            </tr>
            <tr>
                <td>Андрей</td>
                <td><a href="#">Andrey@gmail.com</a></td>
                <td>оптимизация</td>
                <td>16:37</td>
                <td>green</td>
                <td>+38045356624</td>
            </tr>
            <tr>
                <td>Едик</td>
                <td><a href="#">Edic@gmail.com</a></td>
                <td>backend</td>
                <td>14:44</td>
                <td>green</td>
                <td>+33455634553</td>
            </tr>
            <tr>
                <td>Ання</td>
                <td><a href="#">Anna@gmail.com</a></td>
                <td>front-tend</td>
                <td>12:22</td>
                <td>green</td>
                <td>+38093345463</td>
            </tr>
            <tr>
                <td>Денис</td>
                <td><a href="#">Den@gmail.com</a></td>
                <td>backend</td>
                <td>15:44</td>
                <td>green</td>
                <td>+30678432545</td>
            </tr>
            <tr>
                <td>Артур</td>
                <td><a href="#">Artur@gamil.com</a></td>
                <td>JavaScript</td>
                <td>12:44</td>
                <td>green</td>
                <td>+38096435343</td>
            </tr>
        </table>
    </div>

    <div class="content-sm">
        <table cellpadding="10" border="1" width="90%" class="information-person">
            <tr>
                <td>Андрей</td>
            </tr>
            <tr>
                <td><a href="#">Andrey@gmail.com</a></td>
            </tr>
            <tr>
                <td>оптимизация</td>
            </tr>
            <tr>
                <td>16:37</td>
            </tr>
            <tr>
                <td>green</td>
            </tr>
            <tr>
                <td>+38045356624</td>
            </tr>
        </table>

        <table cellpadding="10" border="1" width="90%" class="information-person">
            <tr>
                <td>Едик</td>
            </tr>
            <tr>
                <td><a href="#">Edic@gmail.com</a></td>
            </tr>
            <tr>
                <td>JavaScript</td>
            </tr>
            <tr>
                <td>14:44</td>
            </tr>
            <tr>
                <td>green</td>
            </tr>
            <tr>
                <td>+38096435343</td>
            </tr>
        </table>

        <table cellpadding="10" border="1" width="90%" class="information-person">
            <tr>
                <td>Ання</td>
            </tr>
            <tr>
                <td><a href="#">Anna@gmail.com</a></td>
            </tr>
            <tr>
                <td>front-tend</td>
            </tr>
            <tr>
                <td>12 : 22</td>
            </tr>
            <tr>
                <td>green</td>
            </tr>
            <tr>
                <td>+38096435343</td>
            </tr>
        </table>

        <table cellpadding="10" border="1" width="90%" class="information-person">
            <tr>
                <td>Денис</td>
            </tr>
            <tr>
                <td><a href="#">Den@gmail.com</a></td>
            </tr>
            <tr>
                <td>backend</td>
            </tr>
            <tr>
                <td>15 : 44</td>
            </tr>
            <tr>
                <td>green</td>
            </tr>
            <tr>
                <td>+380678432545</td>
            </tr>
        </table>

        <table cellpadding="10" border="1" width="90%" class="information-person">
            <tr>
                <td>Артур</td>
            </tr>
            <tr>
                <td><a href="#">Artur@gamil.com</a></td>
            </tr>
            <tr>
                <td>JavaScript</td>
            </tr>
            <tr>
                <td>12:44</td>
            </tr>
            <tr>
                <td>green</td>
            </tr>
            <tr>
                <td>+38096435343</td>
            </tr>
        </table>
    </div>

</div>
<script src="js/my-js.js"></script>
</body>
</html>

app/views/application/landing.html.erb
<h1>KJASDHFKJASHDJKASD</h1>

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :[name[ %>
    <%= form.text_field :[name[ %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>[name[</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.[name[ %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>[name[:</strong>
  <%= @customer.[name[ %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScrumTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/task_types/_form.html.erb
<%= form_with(model: task_type, local: true) do |form| %>
  <% if task_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task_type.errors.count, "error") %> prohibited this task_type from being saved:</h2>

      <ul>
      <% task_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :[name[ %>
    <%= form.text_field :[name[ %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/task_types/edit.html.erb
<h1>Editing Task Type</h1>

<%= render 'form', task_type: @task_type %>

<%= link_to 'Show', @task_type %> |
<%= link_to 'Back', task_types_path %>

app/views/task_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Task Types</h1>

<table>
  <thead>
    <tr>
      <th>[name[</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @task_types.each do |task_type| %>
      <tr>
        <td><%= task_type.[name[ %></td>
        <td><%= link_to 'Show', task_type %></td>
        <td><%= link_to 'Edit', edit_task_type_path(task_type) %></td>
        <td><%= link_to 'Destroy', task_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task Type', new_task_type_path %>

app/views/task_types/new.html.erb
<h1>New Task Type</h1>

<%= render 'form', task_type: @task_type %>

<%= link_to 'Back', task_types_path %>

app/views/task_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>[name[:</strong>
  <%= @task_type.[name[ %>
</p>

<%= link_to 'Edit', edit_task_type_path(@task_type) %> |
<%= link_to 'Back', task_types_path %>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.number_field :customer_id %>
  </div>

  <div class="field">
    <%= form.label :type_id %>
    <%= form.number_field :type_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Type</th>
      <th>User</th>
      <th>Title</th>
      <th>Description</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.customer_id %></td>
        <td><%= task.type_id %></td>
        <td><%= task.user_id %></td>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.start_time %></td>
        <td><%= task.end_time %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @task.customer_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @task.type_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @task.user_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @task.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @task.end_time %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>